#pragma once

enum Joint {
    STEERING_JOINT,
    STEERING_JOINT_VEL,
    BOGIE_JOINT,
    BOGIE_JOINT_VEL,
    FRONT_LEFT_WHEEL,
    FRONT_RIGHT_WHEEL,
    BACK_LEFT_WHEEL,
    BACK_RIGHT_WHEEL,
    TRANSITIONING,
};